version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-service-uptime"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sraswznf2zk7"
s3_prefix = "aws-service-uptime"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\""
image_repositories = []
